plugins: fetchart embedart fromfilename chroma check musicbrainz info zero
directory: "/home/lido/media/music/beets/media"
library: "/home/lido/media/music/beets/beets.db"
threaded: yes
original_date: no
per_disc_numbering: no
ignore: AppleDouble ._* *~ .DS_Store
sort_album: albumartist+ year+ album+
original_date: yes

import:
  write: yes
  copy: no
  move: yes
  resume: ask
  incremental: yes
  quiet_fallback: skip
  timid: no
  log: "/home/lido/media/music/beets/beets.log"

embedart:
  auto: yes

zero:
  fields: comments
  update_database: true

paths:
  default: Albums/$albumartist/$original_year - $album%aunique{}/$track - $title
  singleton: Albums/Singles/$artist - $title
  comp: Albums/Various Artists/$original_year - $album%aunique{}/$track - $title
  albumtype:soundtrack: Albums/Various Artists/$original_year - $album%aunique{}/$track - $title

convert:
  auto: no
  ffmpeg: /usr/bin/ffmpeg
  opts: -ab 320k -ac 2 -ar 48000
  max_bitrate: 320
  threads: 1

ui:
  color: yes
  colors:
    text_success: green
    text_warning: yellow
    text_error: red
    text_highlight: red
    text_highlight_minor: lightgray
    action_default: turquoise
    action: blue

format_album: $albumartist - $year - $album
